"""
Auto-YARA rule generator — creates hunting rules from analysis findings.

Generates rules from:
- Unique suspicious strings not found in common software
- Suspicious import combinations
- File-type-specific byte patterns
- Known packer signatures found in this sample
"""

import datetime
import hashlib
import re
from typing import Optional


# Strings commonly found in benign software — exclude from YARA rules
_NOISE_STRINGS = {
    "microsoft", "windows", "system32", "program files", "rundll32",
    "msvcp", "msvcr", "kernel32", "user32", "ntdll", "advapi32",
    "GetProcAddress", "LoadLibraryA", "ExitProcess", "GetLastError",
    "CloseHandle", "CreateFileA", "ReadFile", "WriteFile",
    "memcpy", "malloc", "free", "printf", "sprintf", "strlen",
    "This program cannot be run in DOS mode",
    ".text", ".data", ".rdata", ".rsrc", ".reloc",
    "PADDINGXXPADDING",
}

_MIN_STRING_LEN  = 8
_MAX_STRINGS     = 20
_MAX_IMPORTS     = 10


def generate_yara_rule(analysis: dict, rule_name: Optional[str] = None) -> Optional[str]:
    """
    Generate a YARA rule from analysis findings.
    Returns the rule as a string, or None if there's not enough to generate from.
    """
    fi     = analysis.get("file_info", {})
    static = analysis.get("static", {})
    ai_s   = analysis.get("ai_analysis", {}).get("structured", {})
    intel  = analysis.get("intel", {})

    sha256   = fi.get("hashes", {}).get("sha256", "unknown")
    family   = (ai_s.get("malware_family")
                or intel.get("_summary", {}).get("consensus_family")
                or "unknown")

    if not rule_name:
        short_hash = sha256[:8] if sha256 != "unknown" else "sample"
        safe_family = re.sub(r"[^A-Za-z0-9_]", "_", family)
        rule_name = f"Malyze_{safe_family}_{short_hash}"

    strings_section = _build_strings_section(static)
    condition        = _build_condition(static, strings_section)

    if not strings_section and not condition:
        return None

    # Metadata
    threat_level = (ai_s.get("threat_level")
                    or analysis.get("ai_analysis", {}).get("threat_level", "UNKNOWN"))
    malware_type  = ai_s.get("malware_type", "unknown")
    ttps_str      = ", ".join(
        t.get("id", "") for t in ai_s.get("ttps", []) if t.get("id")
    )[:200]

    meta = [
        f'        description = "Auto-generated by Malyze for sample {sha256[:16]}..."',
        f'        author      = "Malyze Auto-YARA"',
        f'        date        = "{datetime.datetime.utcnow().strftime("%Y-%m-%d")}"',
        f'        hash        = "{sha256}"',
        f'        family      = "{family}"',
        f'        malware_type = "{malware_type}"',
        f'        threat_level = "{threat_level}"',
    ]
    if ttps_str:
        meta.append(f'        mitre_ttps  = "{ttps_str}"')
    if intel.get("_summary", {}).get("known_malware"):
        meta.append(f'        known_malware = true')

    meta_block = "\n".join(meta)
    strings_block = "\n".join(f"        {s}" for s in strings_section) if strings_section else ""

    rule = f"""rule {rule_name} {{
    meta:
{meta_block}
"""
    if strings_block:
        rule += f"""    strings:
{strings_block}
"""
    rule += f"""    condition:
        {condition}
}}
"""
    return rule


def save_yara_rule(analysis: dict, output_path: str) -> Optional[str]:
    """
    Generate and save a YARA rule to a file.
    Returns the file path on success, None if no rule could be generated.
    """
    rule = generate_yara_rule(analysis)
    if not rule:
        return None
    try:
        from pathlib import Path
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(rule, encoding="utf-8")
        return output_path
    except Exception:
        return None


# ── Internal builders ─────────────────────────────────────────────────────────

def _build_strings_section(static: dict) -> list:
    """Build the strings: section entries."""
    entries = []
    seen    = set()

    # 1. Unique suspicious strings from string extraction
    all_strings = static.get("strings", {}).get("strings", [])
    iocs        = static.get("strings", {}).get("iocs", {})

    # Prioritize: API calls, URLs, suspicious keywords, then general strings
    candidates = []
    for cat in ("api_calls", "urls", "suspicious_keywords", "registry", "mutex"):
        for item in iocs.get(cat, [])[:5]:
            candidates.append(str(item))

    # Add notable strings from the full list (skip noise)
    for s in all_strings[:500]:
        if len(s) >= _MIN_STRING_LEN and not _is_noise(s):
            candidates.append(s)

    for s in candidates:
        if len(entries) >= _MAX_STRINGS:
            break
        cleaned = s.strip()
        if len(cleaned) < _MIN_STRING_LEN:
            continue
        key = cleaned.lower()
        if key in seen or _is_noise(cleaned):
            continue
        seen.add(key)
        # Escape special chars for YARA
        escaped = cleaned.replace("\\", "\\\\").replace('"', '\\"')
        var_name = f"$s{len(entries) + 1}"
        entries.append(f'{var_name} = "{escaped}" ascii wide nocase')

    # 2. Suspicious import DLL+function combos
    susp_imports = static.get("pe", {}).get("suspicious_imports", [])
    for imp in susp_imports[:_MAX_IMPORTS]:
        if len(entries) >= _MAX_STRINGS + _MAX_IMPORTS:
            break
        func = imp.split("!")[-1] if "!" in imp else imp
        if func and func not in seen:
            seen.add(func)
            var_name = f"$imp{len(entries) + 1}"
            entries.append(f'$imp{len(entries) + 1} = "{func}" ascii')

    return entries


def _build_condition(static: dict, strings_section: list) -> str:
    """Build the condition: clause."""
    parts = []

    # File type anchors
    file_type = static.get("file_info", {}).get("type", "")
    pe_data   = static.get("pe", {})
    if pe_data and not pe_data.get("error"):
        parts.append("uint16(0) == 0x5A4D")  # MZ header

    # Must match at least some of the strings
    if strings_section:
        n = min(3, len(strings_section))
        if n == 1:
            parts.append("$s1")
        else:
            parts.append(f"{n} of ($s*)")

    if not parts:
        parts.append("true")

    return " and ".join(parts)


def _is_noise(s: str) -> bool:
    """Return True if the string is too generic to be a useful YARA indicator."""
    low = s.lower()
    # Skip very short strings
    if len(s) < _MIN_STRING_LEN:
        return True
    # Skip strings that are all digits or hex
    if re.match(r"^[0-9a-fA-F]+$", s):
        return True
    # Skip known noise
    for noise in _NOISE_STRINGS:
        if noise.lower() in low:
            return True
    # Skip strings that are mostly non-printable or whitespace
    printable = sum(1 for c in s if 32 <= ord(c) < 127)
    if printable / max(len(s), 1) < 0.8:
        return True
    return False
